"""Command-line entrypoint for the JAX AlphaZero trainer."""

from __future__ import annotations

import argparse
import json

from jaxzero.train import TrainingConfig, run_training


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train JAX AlphaZero on pgx Connect Four."
    )
    parser.add_argument("--iterations", type=int, default=10)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument(
        "--sims", "--num-simulations", dest="num_simulations", type=int, default=32
    )
    parser.add_argument("--max-steps", type=int, default=64)
    parser.add_argument(
        "--selfplay-temperature",
        type=float,
        default=1.0,
        help="Visit-count sampling temperature for self-play actions. "
        "Default 1.0 preserves current behavior; 0.0 is greedy.",
    )
    parser.add_argument(
        "--selfplay-temperature-drop-step",
        type=int,
        help="At this zero-based ply and later, use --selfplay-temperature-after-drop.",
    )
    parser.add_argument(
        "--selfplay-temperature-after-drop",
        type=float,
        default=1.0,
        help="Self-play action temperature after the drop step. Default 1.0.",
    )
    parser.add_argument(
        "--selfplay-dirichlet-fraction",
        type=float,
        default=0.25,
        help="Root Dirichlet-noise mixture for self-play MCTS. Default 0.25.",
    )
    parser.add_argument(
        "--selfplay-dirichlet-fraction-drop-step",
        type=int,
        help="At this zero-based ply and later, use "
        "--selfplay-dirichlet-fraction-after-drop.",
    )
    parser.add_argument(
        "--selfplay-dirichlet-fraction-after-drop",
        type=float,
        default=0.25,
        help="Root Dirichlet-noise mixture after the drop step. Default 0.25.",
    )
    parser.add_argument(
        "--selfplay-dirichlet-alpha",
        type=float,
        default=0.3,
        help="Dirichlet alpha for root exploration noise. Default 0.3.",
    )
    parser.add_argument("--channels", type=int, default=64)
    parser.add_argument("--num-res-blocks", type=int, default=5)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--minibatch-size", type=int, default=1024)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--checkpoint", dest="checkpoint_path")
    parser.add_argument(
        "--checkpoint-every",
        type=int,
        help="save iter_NNNN.msgpack next to --checkpoint every N iterations",
    )
    parser.add_argument(
        "--init-checkpoint",
        dest="init_checkpoint",
        help="warm-start training from this checkpoint instead of random init",
    )
    parser.add_argument(
        "--eval-interval",
        type=int,
        help="log vs-random win/draw/loss rates every N iterations",
    )
    parser.add_argument("--eval-games", type=int, default=64)
    parser.add_argument(
        "--replay-capacity",
        type=int,
        help="reuse the most recent N self-play examples across iterations "
        "(default: buffer-free, train only on the current iteration's data)",
    )
    parser.add_argument(
        "--gating-interval",
        type=int,
        help="Every N iterations, play a candidate-vs-best match. On win-rate "
        ">= --gating-threshold the candidate replaces the best net and the "
        "best Elo bumps against itself by the match score. When set, "
        "self-play data is generated by the best net (not the live learner) "
        "for cleaner value targets. Default: off (legacy: self-play uses live).",
    )
    parser.add_argument(
        "--gating-games",
        type=int,
        default=20,
        help="Number of games in each gating match (must be even).",
    )
    parser.add_argument(
        "--gating-threshold",
        type=float,
        default=0.55,
        help="Win-rate over decisive games at or above which the candidate is "
        "promoted to best.",
    )
    parser.add_argument(
        "--value-loss-weight",
        type=float,
        default=1.0,
        help="Scalar multiplier on the value-loss term in the combined loss. "
        "Default 1.0 (no change). Set >1 to attack the value-MAE plateau "
        "(closed alphago-1kc trail: value head is the C4 bottleneck).",
    )
    parser.add_argument(
        "--mirror-augment",
        action="store_true",
        help="Augment each self-play example with its horizontal mirror "
        "(C4 has column symmetry). Doubles training-set size with zero "
        "extra self-play cost; directly boosts value-signal density.",
    )
    parser.add_argument(
        "--solver-rehearsal-positions",
        type=int,
        default=0,
        help="Build a fixed C4 solver-labeled rehearsal pool with this many "
        "sampled positions. Default 0 disables solver-supervised rehearsal.",
    )
    parser.add_argument(
        "--solver-rehearsal-batch-size",
        type=int,
        default=0,
        help="Number of solver-labeled examples to train on each rehearsal "
        "step. Default 0 uses the whole solved rehearsal pool.",
    )
    parser.add_argument(
        "--solver-rehearsal-interval",
        type=int,
        default=1,
        help="Run one solver-supervised rehearsal update every N iterations "
        "when --solver-rehearsal-positions is enabled.",
    )
    parser.add_argument(
        "--solver-rehearsal-seed",
        type=int,
        help="Seed for sampling the rehearsal pool. Default uses training "
        "seed + 10000 so cert/eval seeds can remain held out.",
    )
    parser.add_argument(
        "--solver-rehearsal-target",
        choices=("score", "wdl"),
        default="score",
        help="Policy target for solver rehearsal: 'score' trains only on "
        "distance-optimal moves; 'wdl' trains on all outcome-optimal moves.",
    )
    parser.add_argument(
        "--solver-rehearsal-solver-max-nodes",
        type=int,
        default=250_000,
        help="Per-position solver node budget used when building rehearsal labels.",
    )
    parser.add_argument(
        "--solver-rehearsal-policy-loss-weight",
        type=float,
        default=1.0,
        help="Policy-loss multiplier for solver rehearsal updates. Default 1.0.",
    )
    parser.add_argument(
        "--solver-rehearsal-value-loss-weight",
        type=float,
        default=1.0,
        help="Value-loss multiplier for solver rehearsal updates. Set 0.0 for "
        "policy-only hard-position rehearsal.",
    )
    parser.add_argument(
        "--solver-rehearsal-hard-checkpoint",
        help="Reference checkpoint used to mine hard rehearsal positions. "
        "Requires --solver-rehearsal-hard-pool-size > 0.",
    )
    parser.add_argument(
        "--solver-rehearsal-hard-pool-size",
        type=int,
        default=0,
        help="Sample this many candidate positions, certify the reference "
        "checkpoint, and keep up to --solver-rehearsal-positions policy "
        "misses/high-regret examples. Default 0 disables hard mining.",
    )
    parser.add_argument(
        "--solver-rehearsal-hard-sims",
        type=int,
        default=800,
        help="MCTS sims used when mining hard rehearsal positions. Default 800.",
    )
    parser.add_argument(
        "--solver-rehearsal-anchor-positions",
        type=int,
        default=0,
        help="Add this many random single-WDL-optimal solved positions from the "
        "hard pool as anti-regression anchors. Default 0 disables anchors.",
    )
    parser.add_argument(
        "--weight-decay",
        type=float,
        default=0.0,
        help="When > 0, switch from Adam to AdamW (decoupled L2 reg) with "
        "this weight_decay coefficient. Default 0 keeps Adam (no decay). "
        "Useful if training overshoots and a regularization pull-back "
        "helps the value head plateau.",
    )
    parser.add_argument(
        "--solver-eval-positions",
        type=int,
        default=64,
        help="Every --eval-interval iterations, certify the net against the "
        "solver on this many positions and log eval/c4_blunder_rate "
        "(solver-anchored). Default 64 gives SE ~0.04 on rates near 0.1; "
        "below ~32 the curve discretizes too coarsely to read. Set to 0 to "
        "disable.",
    )
    parser.add_argument("--eval-sims", type=int, default=64)
    parser.add_argument(
        "--arch",
        choices=("resnet", "transformer"),
        default="resnet",
        help="Network tower: 'resnet' (default, uses --channels/--num-res-blocks) "
        "or 'transformer' (uses --d-model/--num-layers/--num-heads/--mlp-dim).",
    )
    parser.add_argument(
        "--d-model",
        type=int,
        default=128,
        help="Transformer embedding/token dimension. Ignored when --arch resnet.",
    )
    parser.add_argument(
        "--num-layers",
        type=int,
        default=6,
        help="Number of transformer blocks. Ignored when --arch resnet.",
    )
    parser.add_argument(
        "--num-heads",
        type=int,
        default=4,
        help="Number of attention heads (must divide --d-model). "
        "Ignored when --arch resnet.",
    )
    parser.add_argument(
        "--mlp-dim",
        type=int,
        default=512,
        help="Transformer per-block MLP hidden dim. Ignored when --arch resnet.",
    )
    parser.add_argument(
        "--use-value-cls-token",
        action="store_true",
        help="Transformer Tier 1: prepend a learnable cls token to the board "
        "sequence; value head reads the cls token only (vs the v1 mean-pool "
        "value head). Fixes the value_mae plateau observed in alphago-6xn.",
    )
    parser.add_argument(
        "--policy-head-style",
        choices=("flatten", "per_column"),
        default="flatten",
        help="Transformer Tier 1: 'flatten' (v1: Linear(H*W*d_model -> action)) "
        "or 'per_column' (shared Linear over each column's H cells -> 1 logit "
        "per column, requires action_size == width). Per-column has stronger "
        "C4 inductive bias and fewer params.",
    )
    parser.add_argument(
        "--input-embed-style",
        choices=("linear", "conv3x3"),
        default="linear",
        help="Transformer Tier 1: 'linear' (v1: Linear(planes -> d_model) per "
        "cell) or 'conv3x3' (3x3 conv patch embedding before tokenization, "
        "AlphaViT style). Conv gives each cell a local receptive field before "
        "self-attention sees the tokens.",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    config = TrainingConfig(
        iterations=args.iterations,
        batch_size=args.batch_size,
        num_simulations=args.num_simulations,
        max_steps=args.max_steps,
        selfplay_temperature=args.selfplay_temperature,
        selfplay_temperature_drop_step=args.selfplay_temperature_drop_step,
        selfplay_temperature_after_drop=args.selfplay_temperature_after_drop,
        selfplay_dirichlet_fraction=args.selfplay_dirichlet_fraction,
        selfplay_dirichlet_fraction_drop_step=(
            args.selfplay_dirichlet_fraction_drop_step
        ),
        selfplay_dirichlet_fraction_after_drop=(
            args.selfplay_dirichlet_fraction_after_drop
        ),
        selfplay_dirichlet_alpha=args.selfplay_dirichlet_alpha,
        channels=args.channels,
        num_res_blocks=args.num_res_blocks,
        learning_rate=args.learning_rate,
        minibatch_size=args.minibatch_size,
        seed=args.seed,
        checkpoint_path=args.checkpoint_path,
        checkpoint_every=args.checkpoint_every,
        init_checkpoint=args.init_checkpoint,
        eval_interval=args.eval_interval,
        eval_games=args.eval_games,
        replay_capacity=args.replay_capacity,
        gating_interval=args.gating_interval,
        gating_games=args.gating_games,
        gating_threshold=args.gating_threshold,
        value_loss_weight=args.value_loss_weight,
        mirror_augment=args.mirror_augment,
        solver_rehearsal_positions=args.solver_rehearsal_positions,
        solver_rehearsal_batch_size=args.solver_rehearsal_batch_size,
        solver_rehearsal_interval=args.solver_rehearsal_interval,
        solver_rehearsal_seed=args.solver_rehearsal_seed,
        solver_rehearsal_target=args.solver_rehearsal_target,
        solver_rehearsal_solver_max_nodes=args.solver_rehearsal_solver_max_nodes,
        solver_rehearsal_policy_loss_weight=(args.solver_rehearsal_policy_loss_weight),
        solver_rehearsal_value_loss_weight=args.solver_rehearsal_value_loss_weight,
        solver_rehearsal_hard_checkpoint=args.solver_rehearsal_hard_checkpoint,
        solver_rehearsal_hard_pool_size=args.solver_rehearsal_hard_pool_size,
        solver_rehearsal_hard_sims=args.solver_rehearsal_hard_sims,
        solver_rehearsal_anchor_positions=args.solver_rehearsal_anchor_positions,
        weight_decay=args.weight_decay,
        arch=args.arch,
        d_model=args.d_model,
        num_layers=args.num_layers,
        num_heads=args.num_heads,
        mlp_dim=args.mlp_dim,
        use_value_cls_token=args.use_value_cls_token,
        policy_head_style=args.policy_head_style,
        input_embed_style=args.input_embed_style,
    )
    extra_evaluator = None
    if args.solver_eval_positions > 0:
        from alphazero.c4_certify import make_solver_evaluator

        extra_evaluator = make_solver_evaluator(
            sample_size=args.solver_eval_positions,
            sims=args.eval_sims,
            seed=args.seed,
        )
    result = run_training(config, extra_evaluator=extra_evaluator)
    for metrics in result.metrics:
        print(json.dumps(metrics, sort_keys=True))
    if result.checkpoint_path is not None:
        print(json.dumps({"checkpoint": result.checkpoint_path}, sort_keys=True))


if __name__ == "__main__":
    main()
