"""Command-line entrypoint for the JAX AlphaZero trainer."""

from __future__ import annotations

import argparse
import json

from jaxzero.train import TrainingConfig, run_training


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train JAX AlphaZero on pgx Connect Four."
    )
    parser.add_argument("--iterations", type=int, default=10)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument(
        "--sims", "--num-simulations", dest="num_simulations", type=int, default=32
    )
    parser.add_argument("--max-steps", type=int, default=64)
    parser.add_argument("--channels", type=int, default=64)
    parser.add_argument("--num-res-blocks", type=int, default=5)
    parser.add_argument("--learning-rate", type=float, default=1e-3)
    parser.add_argument("--minibatch-size", type=int, default=1024)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--checkpoint", dest="checkpoint_path")
    parser.add_argument(
        "--checkpoint-every",
        type=int,
        help="save iter_NNNN.msgpack next to --checkpoint every N iterations",
    )
    parser.add_argument(
        "--init-checkpoint",
        dest="init_checkpoint",
        help="warm-start training from this checkpoint instead of random init",
    )
    parser.add_argument(
        "--eval-interval",
        type=int,
        help="log vs-random win/draw/loss rates every N iterations",
    )
    parser.add_argument("--eval-games", type=int, default=64)
    parser.add_argument(
        "--replay-capacity",
        type=int,
        help="reuse the most recent N self-play examples across iterations "
        "(default: buffer-free, train only on the current iteration's data)",
    )
    parser.add_argument(
        "--gating-interval",
        type=int,
        help="Every N iterations, play a candidate-vs-best match. On win-rate "
        ">= --gating-threshold the candidate replaces the best net and the "
        "best Elo bumps against itself by the match score. When set, "
        "self-play data is generated by the best net (not the live learner) "
        "for cleaner value targets. Default: off (legacy: self-play uses live).",
    )
    parser.add_argument(
        "--gating-games",
        type=int,
        default=20,
        help="Number of games in each gating match (must be even).",
    )
    parser.add_argument(
        "--gating-threshold",
        type=float,
        default=0.55,
        help="Win-rate over decisive games at or above which the candidate is "
        "promoted to best.",
    )
    parser.add_argument(
        "--value-loss-weight",
        type=float,
        default=1.0,
        help="Scalar multiplier on the value-loss term in the combined loss. "
        "Default 1.0 (no change). Set >1 to attack the value-MAE plateau "
        "(closed alphago-1kc trail: value head is the C4 bottleneck).",
    )
    parser.add_argument(
        "--mirror-augment",
        action="store_true",
        help="Augment each self-play example with its horizontal mirror "
        "(C4 has column symmetry). Doubles training-set size with zero "
        "extra self-play cost; directly boosts value-signal density.",
    )
    parser.add_argument(
        "--weight-decay",
        type=float,
        default=0.0,
        help="When > 0, switch from Adam to AdamW (decoupled L2 reg) with "
        "this weight_decay coefficient. Default 0 keeps Adam (no decay). "
        "Useful if training overshoots and a regularization pull-back "
        "helps the value head plateau.",
    )
    parser.add_argument(
        "--solver-eval-positions",
        type=int,
        default=64,
        help="Every --eval-interval iterations, certify the net against the "
        "solver on this many positions and log eval/c4_blunder_rate "
        "(solver-anchored). Default 64 gives SE ~0.04 on rates near 0.1; "
        "below ~32 the curve discretizes too coarsely to read. Set to 0 to "
        "disable.",
    )
    parser.add_argument("--eval-sims", type=int, default=64)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    config = TrainingConfig(
        iterations=args.iterations,
        batch_size=args.batch_size,
        num_simulations=args.num_simulations,
        max_steps=args.max_steps,
        channels=args.channels,
        num_res_blocks=args.num_res_blocks,
        learning_rate=args.learning_rate,
        minibatch_size=args.minibatch_size,
        seed=args.seed,
        checkpoint_path=args.checkpoint_path,
        checkpoint_every=args.checkpoint_every,
        init_checkpoint=args.init_checkpoint,
        eval_interval=args.eval_interval,
        eval_games=args.eval_games,
        replay_capacity=args.replay_capacity,
        gating_interval=args.gating_interval,
        gating_games=args.gating_games,
        gating_threshold=args.gating_threshold,
        value_loss_weight=args.value_loss_weight,
        mirror_augment=args.mirror_augment,
        weight_decay=args.weight_decay,
    )
    extra_evaluator = None
    if args.solver_eval_positions > 0:
        from alphazero.c4_certify import make_solver_evaluator

        extra_evaluator = make_solver_evaluator(
            sample_size=args.solver_eval_positions,
            sims=args.eval_sims,
            seed=args.seed,
        )
    result = run_training(config, extra_evaluator=extra_evaluator)
    for metrics in result.metrics:
        print(json.dumps(metrics, sort_keys=True))
    if result.checkpoint_path is not None:
        print(json.dumps({"checkpoint": result.checkpoint_path}, sort_keys=True))


if __name__ == "__main__":
    main()
